# general settings
name: TexTalker
model_type: TexTalkerModel
num_gpu: 4
manual_seed: 0121
gradient_accumulation_steps: 1
# dataset and data loader settings
datasets:
  train:
    name: TexTalkerV5OffOff
    type: TexTalkerV5OffOffDataset
    dataroot_gt: /data/your_usrname/TexTalkData
    filename_tmpl: '{}'
    io_backend:
      type: disk
    crop_strategy: random
    n_motions: 90
    motion_type: offset
    wrinkle_type: offset
    


    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 10


    # prefetch_mode: ~
    prefetch_mode: cpu
    num_prefetch_queue: 4
    # prefetch_mode: cuda
    # pin_memory: true

  # val:
  #   name: CelebA-HQ-512
  #   type: PairedImageDataset
  #   dataroot_lq: datasets/faces/validation/gt
  #   dataroot_gt: datasets/faces/validation/gt
  #   io_backend:
  #     type: disk
  #   mean: [0.5, 0.5, 0.5]
  #   std: [0.5, 0.5, 0.5]
  #   scale: 1
    
# network structures
network_g:
  type: TexTalker
  n_motions: 90
  n_prev_motions: 15
  use_indicator: True
  audio_model: hubert-cn
  d_style: 72 # number of ID in training set
  feature_dim: 1024
  n_diff_step: 500
trunc_prob1: !!float 0.3
trunc_prob2: !!float 0.4
  

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  #resume_state: ~

train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [120000]
    restart_weights: [1]
    eta_min: !!float 1e-5 # no lr reduce in official vqgan code

  total_iter: 120000

  warmup_iter: 5000  # no warm up
  ema_decay: 0.995 # GFPGAN: 0.5**(32 / (10 * 1000) == 0.998; Unleashing: 0.995
  

  sample_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: none

  # decode_opt:

  # velocity_opt:

  # smooth_opt:

  manual_seed: 0216

# validation settings
val:
  val_freq: !!float 5e10 # no validation
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29422


find_unused_parameters: true
