# general settings
name: VQGAN-Motion
model_type: VQGANMIXModel
num_gpu: 4
manual_seed: 0121

# dataset and data loader settings
datasets:
  train:
    name: TexTalkerMix
    type: TexTalkerMixDataset
    dataroot_gt: /data/your_usrname/TexTalkData
    filename_tmpl: '{}'
    io_backend:
      type: disk
    asset_type: mesh
    in_size: 512
    gt_size: 512

    use_hflip: false
    use_corrupt: false # for VQGAN

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 3
    dataset_enlarge_ratio: 100

    prefetch_mode: cpu
    num_prefetch_queue: 4
    # prefetch_mode: cuda
    # pin_memory: true

  # val:
  #   name: CelebA-HQ-512
  #   type: PairedImageDataset
  #   dataroot_lq: datasets/faces/validation/gt
  #   dataroot_gt: datasets/faces/validation/gt
  #   io_backend:
  #     type: disk
  #   mean: [0.5, 0.5, 0.5]
  #   std: [0.5, 0.5, 0.5]
  #   scale: 1
    
# network structures
network_g:
  type: VQAutoEncoder
  img_size: 512
  emb_dim: 16
  nc: 3
  nf: 64
  ch_mult: [1, 2, 2, 4, 4, 8]
  quantizer: 'nearest'
  codebook_size: 1024

network_d:
  type: VQGANDiscriminator
  nc: 3
  ndf: 64

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: ~
  strict_load_d: true
  resume_state: ~

train:
  optim_g:
    type: Adam
    lr: !!float 2e-5
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 2e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 1e-5 # no lr reduce in official vqgan code

  total_iter: 500000

  warmup_iter: -1  # no warm up
  ema_decay: 0.995 # GFPGAN: 0.5**(32 / (10 * 1000) == 0.998; Unleashing: 0.995

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 1.0
    use_input_norm: true
    range_norm: true

  gan_opt:
    type: GANLoss
    gan_type: hinge
    #gan_type: vanilla
    loss_weight: !!float 0.2 # adaptive_weighting
    #loss_weight: !!float 5e-3

  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 20001
  disc_weight: !!float 0.2
  manual_seed: 0216

# validation settings
val:
  val_freq: !!float 5e10 # no validation
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29444


find_unused_parameters: true
